[project]
name = 'Blockchain-Based-Specialized-Artisanal-Food-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.certification]
path = 'contracts/certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.ingredent-sourcing]
path = 'contracts/ingredent-sourcing.clar'
clarity_version = 2
epoch = 2.5

[contracts.producer-verification]
path = 'contracts/producer-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.production-method]
path = 'contracts/production-method.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
